### ISSUE TITLE
Undefined params lead to sporadic execution failures

### ISSUE THREAD

**Issue by sp-christian** [yaananth/run-notebook#8]
# Symptom
When params are undefined, the execution fails sometimes with
`FileNotFoundError: [Errno 2] No such file or directory: '{}'`

The error is **non deterministc**!
Somtimes the step just runs smooth ... ❓ 

# Configuration
```
- name: run-notebook
      uses: yaananth/run-notebook@v1
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "Testrunner.ipynb"
        #params: "my/unittest-runner-params.json"
```

# Output
```
...
cat /home/runner/work/_temp/nb-runner-scripts/nb-runner.py

import papermill as pm
import os
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from time import sleep

params = {}
paramsPath = '{}'
extraParams = dict({ "secretsPath": '/home/runner/work/_temp/secrets.json' })
if paramsPath:
  with open(paramsPath, 'r') as paramsFile:
    params = json.loads(paramsFile.read())

...

python3 /home/runner/work/_temp/nb-runner-scripts/nb-runner.py
Traceback (most recent call last):
  File "/home/runner/work/_temp/nb-runner-scripts/nb-runner.py", line 13, in <module>
    with open(paramsPath, 'r') as paramsFile:
FileNotFoundError: [Errno 2] No such file or directory: '{}'

```
